# Generated by Django 6.0 on 2026-01-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealResult',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('hubspot_deal_id', models.CharField(max_length=255)),
                ('deal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deal_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('pipeline', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('deal_properties', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_results', to='deals.scanjob')),
            ],
        ),
    ]
