# Generated by Django 6.0 on 2026-01-03 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('deal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_name', models.CharField(max_length=255)),
                ('pipeline', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('close_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.scanjob')),
            ],
        ),
    ]
