# Generated by Django 6.0 on 2026-01-03 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealresult',
            name='close_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dealresult',
            name='deal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dealresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dealresult',
            name='pipeline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dealresult',
            name='stage',
            field=models.CharField(max_length=255),
        ),
    ]
